#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ruyadaherseycom.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hesaplamamotoru")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRuyaTabiri(RuyaTabiri instance);
    partial void UpdateRuyaTabiri(RuyaTabiri instance);
    partial void DeleteRuyaTabiri(RuyaTabiri instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["hesaplamamotoruConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RuyaTabiri> RuyaTabiris
		{
			get
			{
				return this.GetTable<RuyaTabiri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RuyaTabiri")]
	public partial class RuyaTabiri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iKodRuyaTabiri;
		
		private string _cHarf;
		
		private string _cBaslik;
		
		private string _cSeo;
		
		private string _cIcerik;
		
		private System.Nullable<int> _iAktifMi;
		
		private System.Nullable<System.DateTime> _dTarih;
		
		private System.Nullable<int> _iSonGuncelleyenKullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniKodRuyaTabiriChanging(int value);
    partial void OniKodRuyaTabiriChanged();
    partial void OncHarfChanging(string value);
    partial void OncHarfChanged();
    partial void OncBaslikChanging(string value);
    partial void OncBaslikChanged();
    partial void OncSeoChanging(string value);
    partial void OncSeoChanged();
    partial void OncIcerikChanging(string value);
    partial void OncIcerikChanged();
    partial void OniAktifMiChanging(System.Nullable<int> value);
    partial void OniAktifMiChanged();
    partial void OndTarihChanging(System.Nullable<System.DateTime> value);
    partial void OndTarihChanged();
    partial void OniSonGuncelleyenKullaniciChanging(System.Nullable<int> value);
    partial void OniSonGuncelleyenKullaniciChanged();
    #endregion
		
		public RuyaTabiri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iKodRuyaTabiri", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iKodRuyaTabiri
		{
			get
			{
				return this._iKodRuyaTabiri;
			}
			set
			{
				if ((this._iKodRuyaTabiri != value))
				{
					this.OniKodRuyaTabiriChanging(value);
					this.SendPropertyChanging();
					this._iKodRuyaTabiri = value;
					this.SendPropertyChanged("iKodRuyaTabiri");
					this.OniKodRuyaTabiriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cHarf", DbType="NVarChar(50)")]
		public string cHarf
		{
			get
			{
				return this._cHarf;
			}
			set
			{
				if ((this._cHarf != value))
				{
					this.OncHarfChanging(value);
					this.SendPropertyChanging();
					this._cHarf = value;
					this.SendPropertyChanged("cHarf");
					this.OncHarfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cBaslik", DbType="NVarChar(500)")]
		public string cBaslik
		{
			get
			{
				return this._cBaslik;
			}
			set
			{
				if ((this._cBaslik != value))
				{
					this.OncBaslikChanging(value);
					this.SendPropertyChanging();
					this._cBaslik = value;
					this.SendPropertyChanged("cBaslik");
					this.OncBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSeo", DbType="NVarChar(500)")]
		public string cSeo
		{
			get
			{
				return this._cSeo;
			}
			set
			{
				if ((this._cSeo != value))
				{
					this.OncSeoChanging(value);
					this.SendPropertyChanging();
					this._cSeo = value;
					this.SendPropertyChanged("cSeo");
					this.OncSeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cIcerik", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string cIcerik
		{
			get
			{
				return this._cIcerik;
			}
			set
			{
				if ((this._cIcerik != value))
				{
					this.OncIcerikChanging(value);
					this.SendPropertyChanging();
					this._cIcerik = value;
					this.SendPropertyChanged("cIcerik");
					this.OncIcerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iAktifMi", DbType="Int")]
		public System.Nullable<int> iAktifMi
		{
			get
			{
				return this._iAktifMi;
			}
			set
			{
				if ((this._iAktifMi != value))
				{
					this.OniAktifMiChanging(value);
					this.SendPropertyChanging();
					this._iAktifMi = value;
					this.SendPropertyChanged("iAktifMi");
					this.OniAktifMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dTarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> dTarih
		{
			get
			{
				return this._dTarih;
			}
			set
			{
				if ((this._dTarih != value))
				{
					this.OndTarihChanging(value);
					this.SendPropertyChanging();
					this._dTarih = value;
					this.SendPropertyChanged("dTarih");
					this.OndTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iSonGuncelleyenKullanici", DbType="Int")]
		public System.Nullable<int> iSonGuncelleyenKullanici
		{
			get
			{
				return this._iSonGuncelleyenKullanici;
			}
			set
			{
				if ((this._iSonGuncelleyenKullanici != value))
				{
					this.OniSonGuncelleyenKullaniciChanging(value);
					this.SendPropertyChanging();
					this._iSonGuncelleyenKullanici = value;
					this.SendPropertyChanged("iSonGuncelleyenKullanici");
					this.OniSonGuncelleyenKullaniciChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
